# Generated by Django 4.2.1 on 2023-05-30 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestTaskFS', '0006_alter_usermodel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
