# Generated by Django 4.2.1 on 2023-06-04 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestTaskFS', '0007_alter_usermodel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
